-- enumera todos los programas, y todos los géneros vinculados a ese programa, de la base de datos hbtn_0d_tvshows.
-- Si un programa no tiene un género, muestra NULL en la columna de género.
-- Cada registro debe mostrar: tv_shows.title - tv_genres.name
-- Los resultados deben ordenarse en orden ascendente por el título del programa y el nombre del género.
-- Puede usar solo una instrucción SELECT
-- El nombre de la base de datos se pasará como argumento del comando mysql